Update README.md
piranna/fs-fuse pull request #2
Opened 2018-02-19 21:21 UTC by 3n-mb

I adjusted some wording, cause word *next* is confusing. Still, hope that I captured the meaning this was intended to convey.
By the way, nice lib, showing a use of `fuse-binding`.

2018-02-19 23:06 UTC, piranna requested changes

2018-02-19 23:06 UTC, piranna commented on README.md
> +The following `fs` methods directly map to FUSE operations:
They are direct map in their behaviour, but not on their signature. Maybe this can lead to confusion, can you reword it? :-)

2018-02-20 16:49 UTC, 3n-mb commented
@piranna, check the change

2018-02-20 20:37 UTC, piranna approved these changes

2018-02-20 20:38 UTC, merged

2018-02-20 20:38 UTC, piranna commented
> @piranna, check the change

Merged, thanks :-)